openapi: 3.0.0
servers:
  - url: /
info:
  title: zuhlke-data-import-rest
  version: '1.0'
paths:
  '/data/import':
    post:
      tags:
        - zuhlke-data-import-rest
      description: import data from source and store in destination
      operationId: importData
      summary: store data to destination
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
        '400':
          $ref: '#/components/responses/BadRequestException'
        default:
          $ref: '#/components/responses/UnExpectedException'
      deprecated: false
components:
  responses:
    BadRequestException:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    UnExpectedException:
      description: when the server throws unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
        exception:
          type: string
        message:
          type: string
        error:
          type: string
        status:
          type: integer
